version: 2.1

jobs:
    build:
        docker:
            - image: circleci/golang:1
              environment:
                GOLANGCI_LINT_VER:  1.17.1
                DOCKERIZE_VER:      0.11.0
                PGUSER:             postgresuser
                PGPASSWORD:         postgrespass
                PGDATABASE:         postgres
                PGSSLMODE:          disable
            - image: "postgres:11.4"
              environment:
                POSTGRES_USER:      postgresuser
                POSTGRES_PASSWORD:  postgrespass
                POSTGRES_DB:        postgres
        steps:
            - checkout
            - run:
                name: Initialize
                command: |
                    rmdir /go/*/ # fix owner/permission
                    env | grep _VER | sort > /tmp/tools.ver
            - restore_cache:
                keys:
                    - v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                    - v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-
                    - v1-{{ checksum "/tmp/tools.ver" }}-
                    - v1-
            - run:
                name: Install tools
                command: |
                    cd /
                    golangci-lint --version | tee /dev/stderr | grep -wq $GOLANGCI_LINT_VER ||
                        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin v$GOLANGCI_LINT_VER
                    wget -q -O - https://github.com/powerman/dockerize/releases/download/v$DOCKERIZE_VER/dockerize-`uname -s`-`uname -m` |
                        install /dev/stdin /go/bin/dockerize
                    go get -v github.com/mattn/goveralls
            - run:
                name: Wait for dependencies
                command: dockerize -wait tcp://localhost:5432 -timeout 5m
            - run: go test -mod=readonly -v -race -tags=integration ./...
            - run: golangci-lint run
            - run: goveralls -service=circle-ci -flags -tags=integration
            - save_cache:
                when: always
                key: v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                paths:
                    - /go/bin/
                    - /go/pkg/
                    - /go/src/
                    - ~/.cache/go-build/
