version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/go:1.16"
        environment:
          GOFLAGS: "-mod=readonly"
          PGUSER:             postgresuser
          PGPASSWORD:         postgrespass
          PGDATABASE:         postgres
          PGSSLMODE:          disable
      - image: "postgres:12.7"
        environment:
          POSTGRES_USER:      postgresuser
          POSTGRES_PASSWORD:  postgrespass
          POSTGRES_DB:        postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-{{ checksum "go.mod" }}-{{ .Branch }}
            - v3-{{ checksum "go.mod" }}-
            - v3-
      - run: go generate
      - run: .gobincache/golangci-lint run
      - run:
          name: Wait for dependencies
          command: .gobincache/dockerize -wait tcp://localhost:5432 -timeout 5m
      - run: go test -race -tags=integration ./...
      - run: .gobincache/goveralls -service=CircleCI -flags -tags=integration
      - save_cache:
          when: always
          key: v3-{{ checksum "go.mod" }}-{{ .Branch }}
          paths:
            - ~/go/bin/
            - ~/go/pkg/
            - ~/go/src/
            - ~/.cache/go-build/
            - ~/.cache/golangci-lint/
            - .gobincache/

workflows:
  default:
    jobs:
      - test
